# Generated by Django 4.2.27 on 2025-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='srno',
            new_name='sr_no',
        ),
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
